In [31]:
import mlflow
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import mlflow.models
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from mlflow.models import infer_signature


In [4]:
os.getcwd()

'f:\\MLProject\\ML-GenAI\\src\\mlflow'

In [7]:
df1=pd.read_csv('F:\\MLProject\\ML-GenAI\\Data\\voice.csv')
df1.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [11]:
x,y = df1.iloc[:,:-1].values, df1.iloc[:,-1].values
print (x)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print (y)



[[0.05978098 0.06424127 0.03202691 ... 0.0078125  0.         0.        ]
 [0.06600874 0.06731003 0.04022873 ... 0.0546875  0.046875   0.05263158]
 [0.0773155  0.08382942 0.03671846 ... 0.015625   0.0078125  0.04651163]
 ...
 [0.14205626 0.09579843 0.18373124 ... 2.9375     2.9296875  0.19475862]
 [0.14365874 0.09062826 0.18497617 ... 3.59375    3.5859375  0.31100218]
 [0.16550895 0.09288354 0.18304392 ... 0.5546875  0.546875   0.35      ]]
[1 1 1 ... 0 0 0]


In [24]:
params={'penalty':'l2',           # Regularization type: 'l1', 'l2', 'elasticnet', or 'none'
    'C':1.0,                  # Inverse of regularization strength (smaller = stronger regularization)
    'solver':'lbfgs',         # Optimization algorithm ('liblinear', 'saga', 'newton-cg', etc.)
    'max_iter':100,           # Maximum number of iterations
    'random_state':42 ,
    
    'multi_class':'auto'     # Multiclass strategy ('ovr' or 'multinomial') 
}

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = LogisticRegression(**params)

In [26]:
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8123028391167192


f:\MLProject\ML-GenAI\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
f:\MLProject\ML-GenAI\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [27]:
#http://127.0.0.1:5000
mlflow.set_tracking_uri('http://127.0.0.1:5000')

In [ ]:
mlflow.set_experiment('Logistic Regression using Voice dataset')
with mlflow.start_run():
    #log the params
    mlflow.log_params(params)
    #logging the accurary parameter 
    mlflow.log_param('accurary', accuracy)
    #setting the tag
    mlflow.set_tag('model', 'Logistic Regression')
    
    #infer the singature of the model
    infer_sign=infor_signature(x_train, model.predict(x_train))
    ## log the model by giving model name, artifact path , signature(infer_sign) and input example
    model_info=mlflow.sklearn.log_model(
        sk_model=model
        artifact_path='model',
        singature=infer_sign,
        input_example=x_train
        registered_model_name='Logistic Regression Voice Model'
            )

2025/05/05 22:10:08 INFO mlflow.tracking.fluent: Experiment with name 'Logistic Regression using Voice dataset' does not exist. Creating a new experiment.


🏃 View run sedate-dog-880 at: http://127.0.0.1:5000/#/experiments/258884064015000763/runs/5fd5dba211204376a3b5eaf6f928dcba
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/258884064015000763
